Update orange flavor
Signed-off-by: David Cassany <dcassany@suse.com>

diff --git a/examples/orange/Dockerfile b/examples/orange/Dockerfile
--- a/examples/orange/Dockerfile
+++ b/examples/orange/Dockerfile
@@ -1,10 +1,10 @@
 # run `make build` to build local/elemental-toolkit image
-ARG TOOLKIT_REPO
-ARG VERSION
-FROM ${TOOLKIT_REPO}:${VERSION} as TOOLKIT
+ARG TOOLKIT_REPO=local/elemental-toolkit
+ARG VERSION=latest
+FROM ${TOOLKIT_REPO}:${VERSION} AS toolkit
 
 # OS base image of our choice
-FROM ubuntu:23.04 as OS
+FROM ubuntu:24.04 AS os
 ARG REPO
 ARG VERSION
 ENV VERSION=${VERSION}
@@ -49,22 +49,24 @@ RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-ins
   patch \
   netplan.io \
   locales \
+  kbd \
   podman \
+  btrfs-progs \
+  btrfsmaintenance \
   xz-utils
 
-# Create non FHS paths
-RUN mkdir -p /oem /system
+# Hack to prevent systemd-firstboot failures while setting keymap, this is known
+# Debian issue (T_T) https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=790955
+RUN DEBIAN_FRONTEND=noninteractive apt install -y console-data || true && \
+    apt-get clean && rm -rf /var/lib/apt/lists/* && \
+    cd /usr/share/keymaps/i386/qwerty && \
+      find . -name '*.kmap.gz' -exec sh -c 'ln -s "$0" "${0%.kmap.gz}.map.gz"' {} \;
+
+# Symlink grub2-editenv
+RUN ln -sf /usr/bin/grub-editenv /usr/bin/grub2-editenv
 
 # Just add the elemental cli
-COPY --from=TOOLKIT /usr/bin/elemental /usr/bin/elemental
-
-# This is patches are fix upstream dracut, see https://github.com/dracutdevs/dracut/pull/2525
-ADD patches /
-
-RUN cd /usr/lib/dracut && \
-    patch -p 1 -f -i /0001-fix-dmsquash-live-restore-compatibility-with-earlier.patch && \
-    patch -p 1 -f -i /0001-fix-overlayfs-split-overlayfs-mount-in-two-steps.patch && \
-    rm /*.patch
+COPY --from=toolkit /usr/bin/elemental /usr/bin/elemental
 
 # Enable essential services
 RUN systemctl enable systemd-networkd.service
@@ -80,11 +82,11 @@ RUN locale-gen --lang en_US.UTF-8
 RUN elemental --debug init -f
 
 # Update os-release file with some metadata
-RUN echo IMAGE_REPO=\"${REPO}\"         >> /etc/os-release && \
+RUN echo IMAGE_REPO=\"${REPO}\"             >> /etc/os-release && \
     echo IMAGE_TAG=\"${VERSION}\"           >> /etc/os-release && \
-    echo IMAGE=\"${REPO}:${VERSION}\" >> /etc/os-release && \
-    echo TIMESTAMP="`date +'%Y%m%d%H%M%S'`" >> /etc/os-release
-RUN echo GRUB_ENTRY_NAME=\"Elemental\" >> /etc/os-release
+    echo IMAGE=\"${REPO}:${VERSION}\"       >> /etc/os-release && \
+    echo TIMESTAMP="`date +'%Y%m%d%H%M%S'`" >> /etc/os-release && \
+    echo GRUB_ENTRY_NAME=\"Elemental\"      >> /etc/os-release
 
 # Adding specific network configuration based on netplan
 ADD 05_network.yaml /system/oem/05_network.yaml
@@ -92,9 +94,9 @@ ADD 05_network.yaml /system/oem/05_network.yaml
 # Arrange bootloader binaries into /usr/lib/elemental/bootloader
 # this way elemental installer can easily fetch them
 RUN mkdir -p /usr/lib/elemental/bootloader && \
-    cp /usr/lib/grub/x86_64-efi-signed/gcdx64.efi.signed /usr/lib/elemental/bootloader/grubx64.efi && \
+    cp /usr/lib/grub/x86_64-efi-signed/grubx64.efi.signed /usr/lib/elemental/bootloader/grubx64.efi && \
     cp /usr/lib/shim/shimx64.efi.signed.latest /usr/lib/elemental/bootloader/shimx64.efi && \
     cp /usr/lib/shim/mmx64.efi /usr/lib/elemental/bootloader/mmx64.efi
 
 # Good for validation after the build
-CMD /bin/bash
+CMD ["/bin/bash"]
