Store boot assessment variables in grubenv
This commit refactors the boot-assessment logic to run checks
with a customizable service and to store grub variables in
already existing files in EFI partition and OEM.

Also the EFI partition is made accessible in after-*-chroot
hooks. This makes easier to write and manage files in EFI
partition if needed (e.g. grub_oem_env variable file), without
having to relay on mounts or remounts.

Signed-off-by: David Cassany <dcassany@suse.com>

diff --git a/pkg/features/embedded/boot-assessment/usr/sbin/elemental-boot-assessment b/pkg/features/embedded/boot-assessment/usr/sbin/elemental-boot-assessment
--- a/pkg/features/embedded/boot-assessment/usr/sbin/elemental-boot-assessment
+++ b/pkg/features/embedded/boot-assessment/usr/sbin/elemental-boot-assessment
@@ -3,22 +3,27 @@
 declare checkResultsPath="/run/elemental/boot-assessment"
 declare checkersPath="/usr/libexec/elemental-checker"
 declare efiPath="/run/elemental/efi/boot_assessment"
-declare upgradeFailureSentinel="/run/elemental/upgrade_failure"
+declare activeMode="/run/elemental/active_mode"
+declare passiveMode="/run/elemental/passive_mode"
 
 function doBootAssessment {
     local script
     local checker
-    local retCode="0"
+    local retCode=0
 
     mkdir -p "${checkResultsPath}"
 
     # Iterate over elemental checkers
-    for script in "${checkersPath}/*.sh"; do
+    for script in "${checkersPath}"/*; do
         checker=$(basename "${script}")
-        [ -e "${checkResultsPath}/${checker}" ] && continue
+        [ -f "${checkResultsPath}/${checker}" ] && continue
+        [ -x "${script}" ] || continue
         
+        echo "Running checker: ${checker}"
+
         "${script}" check
         if [ $? -ne 0 ]; then
+            >&2 echo "Checker ${checker} failed..."
             retCode=1
         else
             > "${checkResultsPath}/${checker}" 
@@ -28,11 +33,14 @@ function doBootAssessment {
     return "${retCode}"
 }
 
+echo "Starting boot assessment"
+
 doBootAssessment
 if [ $? -ne 0 ]; then
-  echo 1 > "${upgradeFailureSentinel}"
   exit 1
 fi
 
-grub2-editenv "${efiPath}/boot_assessment" set enable_boot_assessment=
-grub2-editenv "${efiPath}/boot_assessment" set boot_assessment_tentative=
+if [ -f "${activeMode}" ]; then
+  grub2-editenv /oem/grubenv unset boot_assessment_check
+fi
+grub2-editenv /oem/grubenv unset last_boot_attempt
